version: '3.8'

services:
  postgres:
    image: postgres
    networks:
      - fpt-test-cms
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fpt_db
    volumes:
      - store-postgres:/var/lib/postgresql/data
networks:
  fpt-test-cms:


volumes:
  store-postgres:
